const wordPairs = [
                { korean: 'test1', german: 'test' },
                { korean: 'test2', german: 'test' },
                { korean: 'test3', german: 'test' },
                { korean: 'test4', german: 'test' },
                { korean: '그나마', german: 'immerhin' },
                { korean: '까만색', german: 'schwarz' },
                { korean: '새우다', german: 'brüten' },
                { korean: '안간힘', german: 'Anstrengung' },
                { korean: '방울', german: 'Tropfen' },
                { korean: '귀신', german: 'Geist' },
                { korean: '억기', german: 'Gedächtnis' },
                { korean: '신입생', german: 'Erstsemester' },
                { korean: '하느님', german: 'Gott' },
                { korean: '미담이', german: 'schöne Geschichte' },
                { korean: '대개', german: 'meistens' },
                { korean: '후배', german: 'jüngerer Kollege' },
                { korean: '충상', german: 'Loyalität' },
                { korean: '다스리다', german: 'regieren' },
                { korean: '통신부', german: 'Kommunikationsministerium' },
                { korean: '포함되다', german: 'enthalten sein' },
                { korean: '군하다', german: 'gnädig' },
                { korean: '상관없이', german: 'unabhängig von' },
                { korean: '마음껏', german: 'nach Herzenslust' },
                { korean: '훨씬', german: 'viel' },
                { korean: '고양이', german: 'Katze' },
                { korean: '일회용품', german: 'Einwegartikel' },
                { korean: '쌀가게', german: 'Reisgeschäft' },
                { korean: '나무라다', german: 'tadeln' },
                { korean: '불잡다', german: 'Feuer fangen' },
                { korean: '만족하다', german: 'zufrieden sein' },
                { korean: '감지', german: 'Erkennung' },
                { korean: '전망하다', german: 'aussichtsreich' },
                { korean: '전시하다', german: 'ausstellen' },
                { korean: '한울한울', german: 'fröhlich' },
                { korean: '살아오다', german: 'überleben' },
                { korean: '김치', german: 'Kimchi' },
                { korean: '안방', german: 'Hauptraum' },
                { korean: '돌아보다', german: 'zurückblicken' },
                { korean: '충학생', german: 'fleißiger Student' },
                { korean: '유발하다', german: 'verursachen' }
            ];

export { wordPairs };